name: gdg_alicante_badges_frontend
description: Frontend for the GDG Alicante Badges generator.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  http: ^1.2.1

dev_dependencies:
  build_runner: ^2.8.0
  build_web_compilers: ^4.2.4
  coolint: ^2.0.1

scripts:
  build: dart run build_runner build -o build
